### ISSUE TITLE
Missing Requirement & change to ln 137 main.py

### ISSUE THREAD

**Issue by scriptsforweirdos** [C-Loftus/YoutubeTakeoutToInvidious#1]
Need to add rich to requirements.txt.

Also, to get this working with current Youtube Takeout playlist format, I had to make the following changes to main.py:

Ln 137 in main.py: 
```df = pandas.read_csv(f, skiprows=2)["Video Id"]```
becomes:
```df = pandas.read_csv(f)["Video ID"]```

**Comment by C-Loftus** [comment]
Ah ok thank you must've missed the requirement. Feel free to open a PR. 

I guess they must've changed the export format. If you have the csv I'd be interested to see what the first few lines look like

**Comment by scriptsforweirdos** [comment]
Will make a note to do a PR when I have time. Have attached csvs for playlist and subs.
[2023-videos.csv](https://github.com/C-Loftus/YoutubeTakeoutToInvidious/files/13541857/2023-videos.csv)
[subscriptions.csv](https://github.com/C-Loftus/YoutubeTakeoutToInvidious/files/13541858/subscriptions.csv)

**Comment by Firefly7-7** [comment]
I had the same issue and fixed both on my end.  Also changed it to open files with the 'with' statement, since that's generally safer, and another issue.  Should I fork and make a pull request from there?

**Comment by C-Loftus** [comment]
Sure that would be great @Firefly7-7  thank you. I am not using YouTube much these days so knowing your solutions works for you with the current YT takeout would be another benefit

**Comment by Firefly7-7** [comment]
ok, done!  Yep, I made the switch like, yesterday, so unless they changed the format again it'll work.

**Comment by C-Loftus** [comment]
Looks good, I have merged. Thanks for the fix! Closing this unless you have other comments. As I am looking over the script, I am realizing it is a bit messy in places, but that is probably something I will fix another day :^)
